make_me:
	mpicc matmult_p2p_blocking.c -o matmult_p2p_blocking
	mpicc matmult_p2p_blocking_all.c -o matmult_p2p_blocking_all
	mpicc matmult_p2p_blocking_flow.c -o matmult_p2p_blocking_flow
	mpicc matmult_p2p_non_blocking.c -o matmult_p2p_non_blocking
	mpicc matmult_collective_comm.c -o matmult_collective_comm